language: node_js
node_js: "10.15"
cache: yarn

_production-job: &production-job
  stage: production
  name: SERVICE_NAME
  script: npx @parameter1/base-cms-newsletter-deployment-tool deploy TENANT_KEY NAMESPACE
  install: skip
  env:
    - "ENVIRONMENT=production"

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - <<: *production-job
      stage: production-started
      name: Deployment Started
      script: npx @parameter1/base-cms-newsletter-deployment-tool notify-started

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - <<: *production-job
      name: All/Multi-site
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy all newsletters

    - <<: *production-job
      name: mundo
      script: npx @parameter1/base-cms-newsletter-deployment-tool deploy mundo newsletters

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - <<: *production-job
      stage: production-finished
      name: Deployment Finished
      script: npx @parameter1/base-cms-newsletter-deployment-tool notify-finished
